annotations:
  artifacthub.io/category: database
  artifacthub.io/changes: |2
        - kind: changed
          description: "Support pgvector image tags (#744)"
          links:
            - name: "Commit 8a69448"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/8a69448"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: PostgreSQL
      url: https://www.postgresql.org
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/postgres
    - name: Application
      url: https://github.com/postgres/postgres
    - name: Docker Image
      url: https://hub.docker.com/_/postgres
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  license: Apache-2.0
apiVersion: v2
appVersion: 18.1.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/cloudpirates
  version: 2.x.x
description: The World's Most Advanced Open Source Relational Database
home: https://www.postgresql.org
icon: https://a.storyblok.com/f/143071/512x512/95e7f13e62/postgres-logo.svg
keywords:
- postgres
- postgresql
- database
- sql
- relational
maintainers:
- email: hello@cloudpirates.io
  name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
name: postgresql
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/postgres
- https://github.com/postgres/postgres
type: application
version: 0.13.6
